name : Upload website to S3

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - uses: jakejarvis/s3-sync-action@master
        with:
            args: --acl public-read --follow-symlinks --delete
        env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCES_KEY_ID: ${{ secrets.AWS_ACCES_KEY_ID }}
            AWS_SECRET_ACCES_KEY: ${{ secrets.AWS_SECRET_ACCES_KEY }}
            AWS_REGION: 'us-east-1'
            SOURCE_DIR: 'Resume_Project_AndreaC'
